[pytest]
testpaths = tests
python_files = test_*.py


# Stelle sicher, dass das Projekt-Root (wo apps/ liegt) im Pythonpfad ist
pythonpath = .


# CRITICAL: Deaktiviere Capture komplett für Python 3.13
addopts = -p no:capture

