sonar.projectKey=jacque-schu_MSE_eVote
sonar.organization=jacque-schu-1
sonar.sources=apps/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.exclusions=tests/**
sonar.sourceEncoding=UTF-8
